multi_map_action_server:
  ros__parameters:
    db_path: "~/ros2_ws/src/wormhole_nav/sql/wormholes.db"
    maps:
      room1: "~/ros2_ws/src/Multi-Map-Navigation-with-Wormhole/wormhole_nav/maps/custom_map.yaml"
      room2: "~/ros2_ws/src/wormhole_nav/maps/maze.yaml"