db_path: ~/wormhole_ws/src/Multi-Map-Navigation-with-Wormhole/wormhole_nav/sql/wormholes.db

maps:
  roomA: ~/wormhole_ws/src/Multi-Map-Navigation-with-Wormhole/wormhole_nav/maps/custom_map.yaml
  roomB: ~/wormhole_ws/src/Multi-Map-Navigation-with-Wormhole/wormhole_nav/maps/maze.yaml